server.port=9090

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ewm_stats}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:stats}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:stats}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.sql.init.mode=always

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
