services:
  stats-server:
    build:
      context: .
      dockerfile: stats-service/stats-server/Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/ewm_stats
      SPRING_DATASOURCE_USERNAME: stats
      SPRING_DATASOURCE_PASSWORD: stats
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy

  stats-db:
    image: postgres:16.1-alpine
    environment:
      POSTGRES_DB: ewm_stats
      POSTGRES_USER: stats
      POSTGRES_PASSWORD: stats
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stats -d ewm_stats"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - stats-db-data:/var/lib/postgresql/data

volumes:
  stats-db-data:
